django_task1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notebook/', include('notebook.urls', namespace='notebook'))
    ]

notebook/urls.py
from django.urls import path

from . import views

app_name = 'notebook'

urlpatterns = [
    path('', views.ContactListView.as_view(), name='contact_list'),
    path('<slug:pk>/edit/', views.contact_edit, name='contact_edit'),
    path(
        'add_contact/', views.ContactCreateView.as_view(),
        name='contact_create'
        )
    ]

notebook/models.py
import re

from django.core.exceptions import ValidationError
from django.db import models


def is_digit(val):
    if re.search(r'[!@$%^&*()_+=<> ,-.  0-9]', val):
        raise ValidationError(
            'Enter only letters', code='not_digit', params={'value': val}
            )


def is_phone(val):
    if not re.search(r'^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\./0-9]*$', val):
        raise ValidationError(
            'Eter only 0-9 digits and +()- symbols', code='not_phone number',
            params={
                'value':
                    val
                }
            )


class Contact(models.Model):
    first_name = models.CharField(max_length=100, validators=[is_digit])
    last_name = models.CharField(max_length=100, validators=[is_digit])
    e_mail = models.EmailField(max_length=100)
    phone_number = models.CharField(max_length=20, validators=[is_phone])
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}-{self.first_name}-{self.last_name}'

notebook/forms.py
from .models import Contact
from bootstrap_modal_forms.forms import BSModalModelForm


class ContactModelForm(BSModalModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'e_mail', 'phone_number']

notebook/views.py
from bootstrap_modal_forms.generic import BSModalCreateView
from django.shortcuts import HttpResponseRedirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView

from .forms import ContactModelForm
from .models import Contact


# Create your views here.
class ContactListView(ListView):
    queryset = Contact.objects.all()
    context_object_name = 'contacts'
    template_name = 'notebook/list.html'
    paginate_by = 15


def contact_edit(request, pk):
    contact = Contact.objects.get(id=int(pk))

    if request.method == 'POST':
        if request.POST.get('add_button') is not None:
            contact.first_name = request.POST['first_name']
            contact.last_name = request.POST['last_name']
            contact.e_mail = request.POST['e_mail']
            contact.phone_number = request.POST['phone_number']
            contact.save()
        return HttpResponseRedirect(reverse('notebook:contact_list'))
    else:
        return render(
            request, 'notebook/update.html', {
                'contact': contact,
                'created_1': contact.created.isoformat('#', 'minutes'),
                'modified_1': contact.modified.isoformat('#', 'minutes')
                }
            )


class ContactCreateView(BSModalCreateView):
    template_name = 'notebook/modal.html'
    form_class = ContactModelForm
    success_message = 'Success: Contact was created.'
    success_url = reverse_lazy('notebook:contact_list')

notebook/templates/notebook/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    {% load static %}
    <link href="{% static "css/blog.css" %}" rel="stylesheet">


    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div id="content">
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#create-contact").modalForm({
            formURL: "{% url 'notebook:contact_create' %}"
        });

    });
</script>

</body>
</html>

notebook/templates/notebook/list.html
{% extends 'notebook/base.html' %}
{% load static %}
{% block title %}Contact list{% endblock %}
{% block content %}
    <div class="container">
        <h2>Contact list</h2>
        <div class="row">
            <div class="col-md-2">
                <p>If you will add new contact</p>
            </div>
            <div class="col-md-2">
                <button id="create-contact" class="btn btn-primary"
                        type="button" name="button">Create contact</button>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Firstname</th>
                <th>Lastname</th>
                <th></th>
                <th>E-mail</th>
                <th>Phone_number</th>
                <th>Created</th>
                <th>Modified</th>
            </tr>
            </thead>
            <tbody>
            {% for item in  contacts %}
                <tr>
                    <td>{{ item.first_name }}</td>
                    <td>{{ item.last_name }}</td>
                    <td><a href='{% url "notebook:contact_edit" item.id %}'
                           class="btn
                    btn-info" role="button">edit</a>
                    </td>
                    <td>{{ item.e_mail }}</td>
                    <td>{{ item.phone_number }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.modified }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% include "notebook/pagination.html" with page=page_obj %}
    </div>
    <!-- Modal -->
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
{% endblock %}

notebook/templates/notebook/modal.html
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title">Create contact</h5>
        <button type="button" class="close" data-dismiss="modal"
                aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">
        {% for field in form %}
            <div class="form-group{% if field.errors %} invalid{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
            Close
        </button>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>

</form>

notebook/templates/notebook/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
    <span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</span>
</div>

notebook/templates/notebook/update.html
{% extends 'notebook/base.html' %}
{% load static %}
{% block title %}Contact edit{% endblock title %}
{% block status_message %}
    {% if form.errors %}
        <div class="alert alert-warning" role="alert">Please, fix the below
            shows errors
        </div>
    {% endif %}
{% endblock status_message %}
{% block content %}

    <div class="edit-form">
    <h3>Edit contact ID-{{ contact.id }}</h3>
    <form action="{% url 'notebook:contact_edit' contact.id %}" method="post"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">First name:</label>
            <input type="text" class="form-control" name="first_name"
                   id="first_name" value={{ contact.first_name}}>
        </div>
        <div class="form-group">
            <label for="last_name">Last name:</label>
            <input type="text" class="form-control" name="last_name"
                   id="last_name" value=
                    {{ contact.last_name }}>
        </div>
        <div class="form-group">
            <label for="e_mail">E-mail:</label>
            <input type="email" class="form-control" name="e_mail" id="e_mail"
                   value=
                    {{ contact.e_mail }}>
        </div>
        <div class="form-group">
            <label for="phone_number">Phone_number:</label>
            <input type="tel" class="form-control" name="phone_number"
                   id="phone_number"
                   value={{ contact.phone_number }}>
        </div>
        <div class="form-group">
            <label for="created">Created:</label>
            <input type="text" class="form-control" id="created" value=
                    {{ created_1 }} readonly>
        </div>
        <div class="form-group">
            <label for="modified">Modified:</label>
            <input type="text" class="form-control" id="modified" value=
                    {{ modified_1 }} readonly>
        </div>
        <button type="submit" class="btn btn-primary" name="add_button">Submit</button>

    </form>
    </div>

{% endblock content %}